build:
	docker-compose build

start:
	docker-compose up php

shell:
	docker-compose run php bash

test:
	docker-compose run php composer run-script test

phpcs:
	docker-compose run php composer run-script cs-check

phpdoc:
	docker-compose run phpdoc

phpdoc-shell:
	docker-compose run phpdoc bash
