build:
	docker-compose build

php:
	docker-compose up php

php-shell:
	docker-compose run php bash

php-test:
	docker-compose run php composer run-script test

php-cs-check:
	docker-compose run php composer run-script cs-check

phpdoc:
	docker-compose run phpdoc

phpdoc-shell:
	docker-compose run phpdoc bash
